name: story_time_customizable
description: A fork of story. Instagram stories like UI with rich animations and even more customizability than the original package.
version: 1.0.6
homepage: https://github.com/MahmoodMakhloof/story_time_customizable

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter:
